name = "quitefragments"
compatibility_date = "2025-04-19"

# Point to the main worker file
main = "dist/_worker.js"

[build]
command = "npm run build"

[site]
bucket = "./dist"

[[kv_namespaces]]
binding = "SESSION"
id = "890853a2d5354c3c95f394c637bdd00b"